### ISSUE TITLE
run main.py find some error.

### ISSUE THREAD

**Issue by ayjin-dev** [dyseo/NewApkPure#1]
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2q  20 Nov 2018) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected Captcha or cloudflare 1020 blocks.
Traceback (most recent call last):
  File "C:/Users/ayjin/Desktop/Develop/googleplay/main.py", line 1, in <module>
    from core.api import Api
  File "C:\Users\ayjin\Desktop\Develop\googleplay\core\__init__.py", line 1, in <module>
    from core.api import Api
  File "C:\Users\ayjin\Desktop\Develop\googleplay\core\api.py", line 1, in <module>
    from core.scrap import Scraping
  File "C:\Users\ayjin\Desktop\Develop\googleplay\core\scrap.py", line 12, in <module>
    class Scraping(object):
  File "C:\Users\ayjin\Desktop\Develop\googleplay\core\scrap.py", line 26, in Scraping
    def get_detail_search(self, urls: str | list) -> List[Dict]:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by ayjin-dev** [comment]
fine...when i switch another device the problem be solved.
maybe we can build this project toghter? could you leave a email we can contact?

**Comment by Alnyz** [comment]
> DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2q 20 Nov 2018) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected Captcha or cloudflare 1020 blocks. Traceback (most recent call last): File "C:/Users/ayjin/Desktop/Develop/googleplay/main.py", line 1, in from core.api import Api File "C:\Users\ayjin\Desktop\Develop\googleplay\core__init__.py", line 1, in from core.api import Api File "C:\Users\ayjin\Desktop\Develop\googleplay\core\api.py", line 1, in from core.scrap import Scraping File "C:\Users\ayjin\Desktop\Develop\googleplay\core\scrap.py", line 12, in class Scraping(object): File "C:\Users\ayjin\Desktop\Develop\googleplay\core\scrap.py", line 26, in Scraping def get_detail_search(self, urls: str | list) -> List[Dict]: TypeError: unsupported operand type(s) for |: 'type' and 'type'

i think you need upgrade your OpenSSL to lasted version

**Comment by Alnyz** [comment]
> fine...when i switch another device the problem be solved. maybe we can build this project toghter? could you leave a email we can contact?

sure, you can fork this repo and just send pull requests or you can contact me at katro.coplax@gmail.com
